# Generated by Django 4.2.4 on 2023-10-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Название датчика"),
                ),
                (
                    "description",
                    models.CharField(max_length=60, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Датчик",
                "verbose_name_plural": "Датчики",
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="Температура")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата измерения"
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement",
                        to="measurement.sensor",
                        verbose_name="Датчик id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Измерение",
                "verbose_name_plural": "Измерения",
            },
        ),
    ]
